"""Data model for UE blueprint paste text (T3D format)."""
from __future__ import annotations

import random
import string
from dataclasses import dataclass, field
from enum import Enum


def _generate_guid() -> str:
    """Generate a 32-char uppercase hex GUID matching UE format.

    MUST be hex only (0-9, A-F). Non-hex characters (G-Z, underscores)
    cause UE to silently drop pin connections when pasting.
    """
    return "".join(random.choices("0123456789ABCDEF", k=32))


class PinDirection(str, Enum):
    INPUT = "EGPD_Input"
    OUTPUT = "EGPD_Output"


class PinCategory(str, Enum):
    EXEC = "exec"
    OBJECT = "object"
    BOOL = "bool"
    REAL = "real"
    STRUCT = "struct"
    DELEGATE = "delegate"
    INT = "int"
    STRING = "string"
    NAME = "name"
    BYTE = "byte"
    CLASS = "class"
    ENUM = "enum"
    INTERFACE = "interface"
    SOFTCLASS = "softclass"
    SOFTOBJECT = "softobject"
    TEXT = "text"
    WILDCARD = "wildcard"
    FLOAT = "float"


@dataclass
class BlueprintPin:
    """A single pin on a blueprint node."""
    pin_name: str
    direction: PinDirection
    category: PinCategory
    pin_id: str = field(default_factory=_generate_guid)
    friendly_name: str = ""
    sub_category: str = ""
    sub_category_object: str = ""
    default_value: str = ""
    container_type: str = ""        # "Array", "Set", "Map", or "" (maps to PinType.ContainerType)
    is_reference: bool = False      # PinType.bIsReference
    is_const: bool = False          # PinType.bIsConst
    is_weak: bool = False           # PinType.bIsWeakPointer
    autogen_default: str = ""       # AutogeneratedDefaultValue
    linked_to: list[tuple[str, str]] = field(default_factory=list)
    hidden: bool = False
    advanced_view: bool = False


@dataclass
class BlueprintNode:
    """A single node in a blueprint graph."""
    node_class: str
    node_name: str
    node_guid: str = field(default_factory=_generate_guid)
    pos_x: int = 0
    pos_y: int = 0
    pins: list[BlueprintPin] = field(default_factory=list)
    properties: dict = field(default_factory=dict)


@dataclass
class BlueprintGraph:
    """A collection of blueprint nodes (flat list, per UE format)."""
    nodes: list[BlueprintNode] = field(default_factory=list)
    asset_path: str = ""     # e.g. "/Game/MyBP.MyBP" — for ExportPath generation
    graph_name: str = "EventGraph"  # Graph name for ExportPath
