"""Serialize BlueprintGraph to UE T3D clipboard paste text format."""
from __future__ import annotations

from ue_flow.t3d_models import (
    BlueprintGraph,
    BlueprintNode,
    BlueprintPin,
    PinDirection,
)


def serialize_pin(pin: BlueprintPin) -> str:
    """Serialize a single pin to a CustomProperties Pin (...) line."""
    parts = [
        f"PinId={pin.pin_id}",
        f'PinName="{pin.pin_name}"',
    ]

    if pin.friendly_name:
        parts.append(f'PinFriendlyName="{pin.friendly_name}"')

    if pin.direction == PinDirection.OUTPUT:
        parts.append('Direction="EGPD_Output"')

    parts.append(f'PinType.PinCategory="{pin.category.value}"')

    # Always emit PinSubCategory (empty string if not set) — UE expects it
    parts.append(f'PinType.PinSubCategory="{pin.sub_category}"')

    if pin.sub_category_object:
        parts.append(f"PinType.PinSubCategoryObject={pin.sub_category_object}")
    else:
        parts.append("PinType.PinSubCategoryObject=None")

    parts.extend([
        f"PinType.PinSubCategoryMemberReference=({pin.pin_sub_category_member_ref})",
        f"PinType.PinValueType=({pin.pin_value_type})",
        f"PinType.ContainerType={pin.container_type or 'None'}",
        f"PinType.bIsReference={pin.is_reference}",
        f"PinType.bIsConst={pin.is_const}",
        f"PinType.bIsWeakPointer={pin.is_weak}",
        "PinType.bIsUObjectWrapper=False",
        "PinType.bSerializeAsSinglePrecisionFloat=False",
    ])

    if pin.default_value:
        parts.append(f'DefaultValue="{pin.default_value}"')

    if pin.default_object:
        parts.append(f"DefaultObject={pin.default_object}")

    if pin.default_text_value:
        parts.append(f'DefaultTextValue="{pin.default_text_value}"')

    if pin.autogen_default:
        parts.append(f'AutogeneratedDefaultValue="{pin.autogen_default}"')

    if pin.linked_to:
        refs = ",".join(f"{name} {pid}" for name, pid in pin.linked_to) + ","
        parts.append(f"LinkedTo=({refs})")

    parts.append("PersistentGuid=00000000000000000000000000000000")
    parts.append(f"bHidden={'True' if pin.hidden else 'False'}")
    parts.append(f"bNotConnectable={'True' if pin.not_connectable else 'False'}")
    parts.append("bDefaultValueIsReadOnly=False")
    parts.append(f"bDefaultValueIsIgnored={'True' if pin.default_value_is_ignored else 'False'}")
    parts.append(f"bAdvancedView={'True' if pin.advanced_view else 'False'}")
    # Trailing comma before closing paren — matches real UE format
    parts.append("bOrphanedPin=False,")

    return "   CustomProperties Pin (" + ",".join(parts) + ")"


def _build_export_path(node: BlueprintNode, asset_path: str, graph_name: str) -> str:
    """Build ExportPath for a node.

    Format: Class'/AssetPath.AssetName:GraphName.NodeName'
    Example: /Script/BlueprintGraph.K2Node_Event'/Game/BP.BP:EventGraph.K2Node_Event_0'
    """
    if not asset_path:
        return ""
    return f"""{node.node_class}'{asset_path}:{graph_name}.{node.node_name}'"""


def serialize_node(node: BlueprintNode, asset_path: str = "", graph_name: str = "EventGraph") -> str:
    """Serialize a single node to a Begin Object...End Object block."""
    # Build header with optional ExportPath
    export_path = _build_export_path(node, asset_path, graph_name)
    if export_path:
        header = f'Begin Object Class={node.node_class} Name="{node.node_name}" ExportPath="{export_path}"'
    else:
        header = f'Begin Object Class={node.node_class} Name="{node.node_name}"'
    lines = [header]

    # Type-specific properties FIRST (matches real UE ordering)
    for key, value in node.properties.items():
        lines.append(f"   {key}={value}")

    # Position
    lines.append(f"   NodePosX={node.pos_x}")
    lines.append(f"   NodePosY={node.pos_y}")

    # GUID
    lines.append(f"   NodeGuid={node.node_guid}")

    # Pins
    for pin in node.pins:
        lines.append(serialize_pin(pin))

    # UserDefinedPin entries
    for udp in node.user_defined_pins:
        lines.append(f"   CustomProperties UserDefinedPin ({udp.get('raw', '')})")

    lines.append("End Object")
    return "\n".join(lines)


def serialize_graph(graph: BlueprintGraph) -> str:
    """Serialize a full graph to UE clipboard paste text."""
    if not graph.nodes:
        return ""
    return "\n\n".join(
        serialize_node(node, graph.asset_path, graph.graph_name)
        for node in graph.nodes
    )


def ensure_bidirectional_links(graph: BlueprintGraph) -> None:
    """Ensure all LinkedTo references are bidirectional.

    For each pin A that links to pin B, adds the reverse link from B to A
    if it doesn't already exist. Modifies pins in-place.
    """
    # Build pin lookup: (node_name, pin_id) -> pin object
    pin_lookup: dict[tuple[str, str], BlueprintPin] = {}
    pin_owner: dict[str, str] = {}  # pin_id -> node_name

    for node in graph.nodes:
        for pin in node.pins:
            pin_lookup[(node.node_name, pin.pin_id)] = pin
            pin_owner[pin.pin_id] = node.node_name

    # For each linked_to entry, ensure reverse exists
    for node in graph.nodes:
        for pin in node.pins:
            for target_node_name, target_pin_id in pin.linked_to:
                target_key = (target_node_name, target_pin_id)
                if target_key in pin_lookup:
                    target_pin = pin_lookup[target_key]
                    reverse = (node.node_name, pin.pin_id)
                    if reverse not in target_pin.linked_to:
                        target_pin.linked_to.append(reverse)
