/**
 * Serialize React Flow state back to UE T3D clipboard paste text.
 *
 * This is the browser-side inverse of the Python t3d_serializer.py.
 * It converts the current React Flow nodes/edges back to valid T3D text
 * that can be pasted into the UE editor.
 */
import type { AnyFlowNode, BlueprintFlowEdge, FlowNodeData } from '../types/flow-types';
import type { UEPin } from '../types/ue-graph';
import type { PinCategory } from '../types/pin-types';
import { qualifyNodeClass, synthesizeNodePropertiesWithDB } from '../utils/ue-references';
import { lookupFunction } from '../utils/signature-db';

// ---------------------------------------------------------------------------
// Pin ID hex sanitization — UE requires 32-char hex-only pin IDs
// ---------------------------------------------------------------------------

const HEX_ONLY_RE = /^[0-9A-Fa-f]+$/;

/**
 * Deterministically convert a non-hex pin ID to a valid 32-char uppercase hex GUID.
 * Uses a simple hash to ensure consistency: the same input always produces the same output.
 * If the ID is already valid hex (32 chars), returns it as-is.
 */
function toHexPinId(id: string): string {
  if (id.length === 32 && HEX_ONLY_RE.test(id)) return id.toUpperCase();
  // Simple deterministic hash: convert each char code to hex, pad/truncate to 32
  let hash = '';
  for (let i = 0; i < id.length; i++) {
    hash += id.charCodeAt(i).toString(16).padStart(2, '0');
  }
  // Pad with zeros or truncate to exactly 32 chars
  return hash.padEnd(32, '0').slice(0, 32).toUpperCase();
}

/**
 * Build a consistent pin ID mapping for the entire export.
 * Every pin ID referenced anywhere (pins, edges) gets a stable hex equivalent.
 */
function buildPinIdMap(nodes: AnyFlowNode[], edges: BlueprintFlowEdge[]): Map<string, string> {
  const map = new Map<string, string>();
  const usedIds = new Set<string>();

  function mapId(id: string): string {
    if (map.has(id)) return map.get(id)!;
    let hex = toHexPinId(id);
    // Handle collisions by incrementing last digit
    while (usedIds.has(hex)) {
      const last = parseInt(hex.slice(-1), 16);
      hex = hex.slice(0, -1) + ((last + 1) % 16).toString(16).toUpperCase();
    }
    map.set(id, hex);
    usedIds.add(hex);
    return hex;
  }

  for (const node of nodes) {
    if (node.type === 'commentNode') continue;
    const data = node.data as FlowNodeData;
    for (const pin of data.pins) {
      mapId(pin.id);
    }
  }
  for (const edge of edges) {
    if (edge.sourceHandle) mapId(edge.sourceHandle);
    if (edge.targetHandle) mapId(edge.targetHandle);
  }

  return map;
}

function serializePinWithLinks(
  pin: UEPin,
  linkedTo: Array<{ nodeName: string; pinId: string }>,
  pinIdMap: Map<string, string>,
): string {
  const hexId = pinIdMap.get(pin.id) ?? toHexPinId(pin.id);
  const parts: string[] = [
    `PinId=${hexId}`,
    `PinName="${pin.name}"`,
  ];

  if (pin.friendlyName) {
    parts.push(`PinFriendlyName="${pin.friendlyName}"`);
  }

  if (pin.direction === 'output') {
    parts.push('Direction="EGPD_Output"');
  }

  parts.push(`PinType.PinCategory="${pin.category}"`);
  parts.push(`PinType.PinSubCategory="${pin.subCategory}"`);

  if (pin.subCategoryObject) {
    parts.push(`PinType.PinSubCategoryObject=${pin.subCategoryObject}`);
  } else {
    parts.push('PinType.PinSubCategoryObject=None');
  }

  parts.push(
    `PinType.PinSubCategoryMemberReference=${pin.pinSubCategoryMemberReference || '()'}`,
    'PinType.PinValueType=()',
    `PinType.ContainerType=${pin.containerType || 'None'}`,
    `PinType.bIsReference=${pin.isReference ? 'True' : 'False'}`,
    `PinType.bIsConst=${pin.isConst ? 'True' : 'False'}`,
    `PinType.bIsWeakPointer=${pin.isWeak ? 'True' : 'False'}`,
    'PinType.bIsUObjectWrapper=False',
    'PinType.bSerializeAsSinglePrecisionFloat=False',
  );

  if (pin.defaultValue) {
    parts.push(`DefaultValue="${pin.defaultValue}"`);
  }
  if (pin.autogeneratedDefaultValue) {
    parts.push(`AutogeneratedDefaultValue="${pin.autogeneratedDefaultValue}"`);
  }

  if (linkedTo.length > 0) {
    const refs = linkedTo.map(l => {
      const hexPinId = pinIdMap.get(l.pinId) ?? toHexPinId(l.pinId);
      return `${l.nodeName} ${hexPinId}`;
    }).join(',') + ',';
    parts.push(`LinkedTo=(${refs})`);
  }

  parts.push('PersistentGuid=00000000000000000000000000000000');
  parts.push(`bHidden=${pin.hidden ? 'True' : 'False'}`);
  parts.push('bNotConnectable=False');
  parts.push('bDefaultValueIsReadOnly=False');
  parts.push('bDefaultValueIsIgnored=False');
  parts.push(`bAdvancedView=${pin.advancedView ? 'True' : 'False'}`);
  parts.push('bOrphanedPin=False,');

  return '   CustomProperties Pin (' + parts.join(',') + ')';
}

interface PinLinkInfo {
  nodeName: string;
  pinId: string;
}

/**
 * Build a map of (nodeId, pinId) -> linked targets from the edge array.
 * Returns a map for both source and target directions (bidirectional links).
 */
function buildLinkedToMap(
  edges: BlueprintFlowEdge[],
): Map<string, PinLinkInfo[]> {
  const map = new Map<string, PinLinkInfo[]>();

  for (const edge of edges) {
    // Source pin -> target
    const sourceKey = `${edge.source}:${edge.sourceHandle}`;
    if (!map.has(sourceKey)) map.set(sourceKey, []);
    map.get(sourceKey)!.push({
      nodeName: edge.target,
      pinId: edge.targetHandle ?? '',
    });

    // Target pin -> source (bidirectional)
    const targetKey = `${edge.target}:${edge.targetHandle}`;
    if (!map.has(targetKey)) map.set(targetKey, []);
    map.get(targetKey)!.push({
      nodeName: edge.source,
      pinId: edge.sourceHandle ?? '',
    });
  }

  return map;
}

// ---------------------------------------------------------------------------
// Hidden pin injection for UE paste-back accuracy
// ---------------------------------------------------------------------------

function makeHiddenPin(
  name: string,
  direction: 'input' | 'output',
  category: string,
  opts: { isConst?: boolean; defaultValue?: string } = {},
): UEPin {
  return {
    id: `hidden-${name.replace(/\s+/g, '-').toLowerCase()}`,
    name,
    friendlyName: name,
    direction,
    category: category as PinCategory,
    subCategory: '',
    subCategoryObject: '',
    containerType: '',
    defaultValue: opts.defaultValue ?? '',
    isReference: false,
    isConst: opts.isConst ?? false,
    isWeak: false,
    hidden: true,
    advancedView: false,
  };
}

/** Extract MemberName from a FunctionReference property string. */
function extractMemberName(props: Record<string, unknown>): string | undefined {
  const val = String(props['FunctionReference'] ?? '');
  const match = val.match(/MemberName="([^"]+)"/);
  return match?.[1];
}

/**
 * Get hidden pins that K2Node_CallFunction needs for UE paste-back.
 * Only injects pins not already present in the node's pin list.
 */
function getHiddenPinsForNode(data: FlowNodeData): UEPin[] {
  const shortClass = data.nodeClass.includes('.') ? data.nodeClass.split('.').pop()! : data.nodeClass;
  if (shortClass !== 'K2Node_CallFunction') return [];

  const existingNames = new Set(data.pins.map((p) => p.name));
  const hidden: UEPin[] = [];

  // self pin
  if (!existingNames.has('self')) {
    hidden.push(makeHiddenPin('self', 'input', 'object'));
  }

  // WorldContextObject pin
  if (!existingNames.has('WorldContextObject')) {
    hidden.push(makeHiddenPin('WorldContextObject', 'input', 'object', { isConst: true }));
  }

  // LatentInfo for latent functions (Delay, etc.)
  if (!existingNames.has('LatentInfo')) {
    const memberName = extractMemberName(data.properties);
    if (memberName) {
      const sig = lookupFunction(memberName);
      if (sig?.isLatent) {
        hidden.push(makeHiddenPin('LatentInfo', 'input', 'struct', {
          defaultValue: '(Linkage=-1,UUID=-1,ExecutionFunction="",CallbackTarget=None)',
        }));
      }
    }
  }

  return hidden;
}

// ---------------------------------------------------------------------------
// nodeGuid validation for export
// ---------------------------------------------------------------------------

const VALID_GUID_RE = /^[0-9A-F]{32}$/;

function generateExportGuid(): string {
  const hex = '0123456789ABCDEF';
  let guid = '';
  for (let i = 0; i < 32; i++) guid += hex[Math.floor(Math.random() * 16)];
  return guid;
}

/**
 * Convert React Flow nodes and edges back to UE T3D paste text.
 */
export function flowToT3D(nodes: AnyFlowNode[], edges: BlueprintFlowEdge[], assetPath?: string): string {
  const linkedToMap = buildLinkedToMap(edges);
  const pinIdMap = buildPinIdMap(nodes, edges);
  const blocks: string[] = [];

  // Deduplicate nodeGuids across all nodes
  const usedGuids = new Set<string>();

  for (const node of nodes) {
    if (node.type === 'commentNode') {
      // Comment nodes use EdGraphNode_Comment format
      const data = node.data;
      const cLines: string[] = [];
      const commentClass = '/Script/UnrealEd.EdGraphNode_Comment';
      const commentExport = assetPath
        ? ` ExportPath="${commentClass}'${assetPath}:EventGraph.${node.id}'"`
        : '';
      cLines.push(`Begin Object Class=${commentClass} Name="${node.id}"${commentExport}`);
      cLines.push(`   NodePosX=${Math.round(node.position.x)}`);
      cLines.push(`   NodePosY=${Math.round(node.position.y)}`);
      const nodeWidth = node.initialWidth ?? (data.properties?.sizeX ? Number(data.properties.sizeX) : undefined);
      const nodeHeight = node.initialHeight ?? (data.properties?.sizeY ? Number(data.properties.sizeY) : undefined);
      if (nodeWidth) cLines.push(`   NodeWidth=${Math.round(nodeWidth)}`);
      if (nodeHeight) cLines.push(`   NodeHeight=${Math.round(nodeHeight)}`);
      cLines.push(`   NodeComment="${data.title ?? 'Comment'}"`);
      if (data.nodeGuid) cLines.push(`   NodeGuid=${data.nodeGuid}`);
      const commentColor = data.properties?.CommentColor;
      if (commentColor) cLines.push(`   CommentColor=${commentColor}`);
      cLines.push(`   MoveMode=${data.properties?.MoveMode ?? 1}`);
      const fontSize = data.properties?.FontSize;
      if (fontSize !== undefined) cLines.push(`   FontSize=${fontSize}`);
      const bubblePinned = data.properties?.bCommentBubblePinned;
      if (bubblePinned !== undefined) {
        cLines.push(`   bCommentBubblePinned=${bubblePinned}`);
        if (String(bubblePinned) === 'True') cLines.push('   bCommentBubbleVisible=True');
      }
      cLines.push('End Object');
      blocks.push(cLines.join('\n'));
      continue;
    }

    // Blueprint node
    const data: FlowNodeData = node.data;
    const lines: string[] = [];
    const fullClass = qualifyNodeClass(data.nodeClass);

    // Header
    const exportPath = assetPath
      ? ` ExportPath="${fullClass}'${assetPath}:EventGraph.${node.id}'"`
      : '';
    lines.push(`Begin Object Class=${fullClass} Name="${node.id}"${exportPath}`);

    // Properties (synthesize missing UE-required properties)
    const props = synthesizeNodePropertiesWithDB(data.nodeClass, data.title, data.properties);
    for (const [key, value] of Object.entries(props)) {
      // Strip trailing \r that may have leaked from CRLF line endings during parse
      const clean = String(value).replace(/\r$/, '');
      lines.push(`   ${key}=${clean}`);
    }

    // Position (use React Flow position, rounded to int)
    lines.push(`   NodePosX=${Math.round(node.position.x)}`);
    lines.push(`   NodePosY=${Math.round(node.position.y)}`);

    // GUID — ensure 32-char hex, deduplicate
    let nodeGuid = data.nodeGuid;
    if (!VALID_GUID_RE.test(nodeGuid) || usedGuids.has(nodeGuid)) {
      nodeGuid = generateExportGuid();
      while (usedGuids.has(nodeGuid)) nodeGuid = generateExportGuid();
    }
    usedGuids.add(nodeGuid);
    lines.push(`   NodeGuid=${nodeGuid}`);

    // Pins with linked_to — reads data.pins which now contains edited defaultValues
    for (const pin of data.pins) {
      const pinKey = `${node.id}:${pin.id}`;
      const linked = linkedToMap.get(pinKey) ?? [];
      lines.push(serializePinWithLinks(pin, linked, pinIdMap));
    }

    // Inject hidden pins for UE paste-back (self, WorldContextObject, LatentInfo)
    const hiddenPins = getHiddenPinsForNode(data);
    for (const pin of hiddenPins) {
      lines.push(serializePinWithLinks(pin, [], pinIdMap));
    }

    lines.push('End Object');
    blocks.push(lines.join('\n'));
  }

  return blocks.join('\n\n');
}
