import type { PinCategory } from './pin-types';

export interface UEPin {
  id: string;
  name: string;
  friendlyName: string;
  direction: 'input' | 'output';
  category: PinCategory;
  subCategory: string;
  subCategoryObject: string;
  containerType: '' | 'Array' | 'Set' | 'Map';
  defaultValue: string;
  autogeneratedDefaultValue?: string;
  defaultObject?: string;
  isReference: boolean;
  isConst: boolean;
  isWeak: boolean;
  hidden: boolean;
  advancedView: boolean;
  description?: string;
  pinSubCategoryMemberReference?: string;
  /** For Map container pins: the value type of the map. */
  valueType?: { category: PinCategory; subCategory?: string; subCategoryObject?: string };
  /** Resolved type when a wildcard pin is locked by a connection. */
  resolvedCategory?: string;
  /** Resolved sub-type (struct/enum name) when a wildcard pin is locked. */
  resolvedSubCategoryObject?: string;
}

export interface UENode {
  id: string;
  type: string;
  nodeClass: string;
  nodeGuid: string;
  position: { x: number; y: number };
  title: string;
  description?: string;
  category?: string;
  properties: Record<string, unknown>;
  pins: UEPin[];
}

export interface UEEdge {
  id: string;
  source: string;
  sourcePin: string;
  target: string;
  targetPin: string;
  category: PinCategory;
}

export interface UEGraphJSON {
  metadata: {
    title: string;
    assetPath: string;
  };
  nodes: UENode[];
  edges: UEEdge[];
  summary?: string;
}

/** A param entry can be a "name: Type" string or a {name, type} object. */
export type SidebarParam = string | { name: string; type: string };

/** A single editable property field in the details panel. */
export interface PropertyField {
  value: string | number | boolean | number[];
  type: 'string' | 'number' | 'bool' | 'vector' | 'enum' | 'segmented' | 'array';
  options?: string[];
}

export interface UEMultiGraphJSON {
  metadata: { title: string; blueprintName?: string; assetPath?: string };
  graphs: Record<string, UEGraphJSON>;
  events: Array<{
    name: string;
    params?: SidebarParam[];
    inputs?: SidebarParam[];
    replicates?: 'NotReplicated' | 'Multicast' | 'RunOnServer' | 'RunOnClient';
    reliable?: boolean;
    callInEditor?: boolean;
    accessSpecifier?: 'Public' | 'Protected' | 'Private';
    keywords?: string;
  }>;
  functions: Array<{
    name: string;
    category?: string;
    params?: SidebarParam[];
    returns?: SidebarParam[];
    inputs?: SidebarParam[];
    outputs?: SidebarParam[];
    pure?: boolean;
    description?: string;
    keywords?: string;
    compactTitle?: string;
    callInEditor?: boolean;
    accessSpecifier?: 'Public' | 'Protected' | 'Private';
  }>;
  variables: Array<{ name: string; type: string; category?: string; default?: string; replicated?: boolean; replicationMode?: 'Replicated' | 'RepNotify' | 'ServerRPC' | 'ClientRPC' | 'MulticastRPC'; containerType?: 'Array' | 'Set' | 'Map'; innerType?: string; keyType?: string; instanceEditable?: boolean; exposeOnSpawn?: boolean; private?: boolean; transient?: boolean; saveGame?: boolean }>;
  components?: Array<{ name: string; class: string; parent?: string; properties?: Record<string, Record<string, PropertyField>> }>;
  macros?: Array<{ name: string; category?: string; inputs?: SidebarParam[]; outputs?: SidebarParam[] }>;
  structs: Array<{ name: string; fields: Array<{ name: string; type: string; default?: string }> }>;
  delegates: Array<{ name: string; signature?: string; params?: SidebarParam[] }>;
  dataTables: Record<string, { sampleRows?: unknown[]; columns?: string[] }>;
  comparison: Record<string, { before: number; after: number }>;
}
